language: node_js
node_js:
- 10.16.3
branches:
  only:
  - production
cache:
  npm: false
before_install:
- openssl aes-256-cbc -K $encrypted_d39d4435ff34_key -iv $encrypted_d39d4435ff34_iv
  -in secret.json.enc -out secret.json -d
install:
- npm i
deploy:
  provider: script
  skip_cleanup: true
  script: npm run publish
  on: production
